# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/diego/Documentos/Facultad/Algoritmos/tp3/alumnos

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/diego/Documentos/Facultad/Algoritmos/tp3/alumnos

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/diego/Documentos/Facultad/Algoritmos/tp3/alumnos/CMakeFiles /home/diego/Documentos/Facultad/Algoritmos/tp3/alumnos/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/diego/Documentos/Facultad/Algoritmos/tp3/alumnos/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named correrTests

# Build rule for target.
correrTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 correrTests
.PHONY : correrTests

# fast build rule for target.
correrTests/fast:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/build
.PHONY : correrTests/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f tests/google-test/CMakeFiles/gtest_main.dir/build.make tests/google-test/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f tests/google-test/CMakeFiles/gtest.dir/build.make tests/google-test/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

src/Calculadora.o: src/Calculadora.cpp.o

.PHONY : src/Calculadora.o

# target to build an object file
src/Calculadora.cpp.o:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Calculadora.cpp.o
.PHONY : src/Calculadora.cpp.o

src/Calculadora.i: src/Calculadora.cpp.i

.PHONY : src/Calculadora.i

# target to preprocess a source file
src/Calculadora.cpp.i:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Calculadora.cpp.i
.PHONY : src/Calculadora.cpp.i

src/Calculadora.s: src/Calculadora.cpp.s

.PHONY : src/Calculadora.s

# target to generate assembly for a file
src/Calculadora.cpp.s:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Calculadora.cpp.s
.PHONY : src/Calculadora.cpp.s

src/Driver.o: src/Driver.cpp.o

.PHONY : src/Driver.o

# target to build an object file
src/Driver.cpp.o:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Driver.cpp.o
.PHONY : src/Driver.cpp.o

src/Driver.i: src/Driver.cpp.i

.PHONY : src/Driver.i

# target to preprocess a source file
src/Driver.cpp.i:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Driver.cpp.i
.PHONY : src/Driver.cpp.i

src/Driver.s: src/Driver.cpp.s

.PHONY : src/Driver.s

# target to generate assembly for a file
src/Driver.cpp.s:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Driver.cpp.s
.PHONY : src/Driver.cpp.s

src/Instruccion.o: src/Instruccion.cpp.o

.PHONY : src/Instruccion.o

# target to build an object file
src/Instruccion.cpp.o:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Instruccion.cpp.o
.PHONY : src/Instruccion.cpp.o

src/Instruccion.i: src/Instruccion.cpp.i

.PHONY : src/Instruccion.i

# target to preprocess a source file
src/Instruccion.cpp.i:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Instruccion.cpp.i
.PHONY : src/Instruccion.cpp.i

src/Instruccion.s: src/Instruccion.cpp.s

.PHONY : src/Instruccion.s

# target to generate assembly for a file
src/Instruccion.cpp.s:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Instruccion.cpp.s
.PHONY : src/Instruccion.cpp.s

src/Programa.o: src/Programa.cpp.o

.PHONY : src/Programa.o

# target to build an object file
src/Programa.cpp.o:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Programa.cpp.o
.PHONY : src/Programa.cpp.o

src/Programa.i: src/Programa.cpp.i

.PHONY : src/Programa.i

# target to preprocess a source file
src/Programa.cpp.i:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Programa.cpp.i
.PHONY : src/Programa.cpp.i

src/Programa.s: src/Programa.cpp.s

.PHONY : src/Programa.s

# target to generate assembly for a file
src/Programa.cpp.s:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Programa.cpp.s
.PHONY : src/Programa.cpp.s

tests/test_driver.o: tests/test_driver.cpp.o

.PHONY : tests/test_driver.o

# target to build an object file
tests/test_driver.cpp.o:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/tests/test_driver.cpp.o
.PHONY : tests/test_driver.cpp.o

tests/test_driver.i: tests/test_driver.cpp.i

.PHONY : tests/test_driver.i

# target to preprocess a source file
tests/test_driver.cpp.i:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/tests/test_driver.cpp.i
.PHONY : tests/test_driver.cpp.i

tests/test_driver.s: tests/test_driver.cpp.s

.PHONY : tests/test_driver.s

# target to generate assembly for a file
tests/test_driver.cpp.s:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/tests/test_driver.cpp.s
.PHONY : tests/test_driver.cpp.s

tests/test_ventana.o: tests/test_ventana.cpp.o

.PHONY : tests/test_ventana.o

# target to build an object file
tests/test_ventana.cpp.o:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/tests/test_ventana.cpp.o
.PHONY : tests/test_ventana.cpp.o

tests/test_ventana.i: tests/test_ventana.cpp.i

.PHONY : tests/test_ventana.i

# target to preprocess a source file
tests/test_ventana.cpp.i:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/tests/test_ventana.cpp.i
.PHONY : tests/test_ventana.cpp.i

tests/test_ventana.s: tests/test_ventana.cpp.s

.PHONY : tests/test_ventana.s

# target to generate assembly for a file
tests/test_ventana.cpp.s:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/tests/test_ventana.cpp.s
.PHONY : tests/test_ventana.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... correrTests"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... src/Calculadora.o"
	@echo "... src/Calculadora.i"
	@echo "... src/Calculadora.s"
	@echo "... src/Driver.o"
	@echo "... src/Driver.i"
	@echo "... src/Driver.s"
	@echo "... src/Instruccion.o"
	@echo "... src/Instruccion.i"
	@echo "... src/Instruccion.s"
	@echo "... src/Programa.o"
	@echo "... src/Programa.i"
	@echo "... src/Programa.s"
	@echo "... tests/test_driver.o"
	@echo "... tests/test_driver.i"
	@echo "... tests/test_driver.s"
	@echo "... tests/test_ventana.o"
	@echo "... tests/test_ventana.i"
	@echo "... tests/test_ventana.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

