# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "D:\JetBrains\CLion 2017.2.3\bin\cmake\bin\cmake.exe"

# The command to remove a file.
RM = "D:\JetBrains\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = E:\Proyectos\AEDTP3Calculadora

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = E:\Proyectos\AEDTP3Calculadora

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"D:\JetBrains\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"D:\JetBrains\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"D:\JetBrains\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"D:\JetBrains\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"D:\JetBrains\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"D:\JetBrains\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"D:\JetBrains\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"D:\JetBrains\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start E:\Proyectos\AEDTP3Calculadora\CMakeFiles E:\Proyectos\AEDTP3Calculadora\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start E:\Proyectos\AEDTP3Calculadora\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named correrTests

# Build rule for target.
correrTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 correrTests
.PHONY : correrTests

# fast build rule for target.
correrTests/fast:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/build
.PHONY : correrTests/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f tests\google-test\CMakeFiles\gtest.dir\build.make tests/google-test/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f tests\google-test\CMakeFiles\gtest_main.dir\build.make tests/google-test/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/Calculadora.obj: src/Calculadora.cpp.obj

.PHONY : src/Calculadora.obj

# target to build an object file
src/Calculadora.cpp.obj:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/src/Calculadora.cpp.obj
.PHONY : src/Calculadora.cpp.obj

src/Calculadora.i: src/Calculadora.cpp.i

.PHONY : src/Calculadora.i

# target to preprocess a source file
src/Calculadora.cpp.i:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/src/Calculadora.cpp.i
.PHONY : src/Calculadora.cpp.i

src/Calculadora.s: src/Calculadora.cpp.s

.PHONY : src/Calculadora.s

# target to generate assembly for a file
src/Calculadora.cpp.s:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/src/Calculadora.cpp.s
.PHONY : src/Calculadora.cpp.s

src/Driver.obj: src/Driver.cpp.obj

.PHONY : src/Driver.obj

# target to build an object file
src/Driver.cpp.obj:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/src/Driver.cpp.obj
.PHONY : src/Driver.cpp.obj

src/Driver.i: src/Driver.cpp.i

.PHONY : src/Driver.i

# target to preprocess a source file
src/Driver.cpp.i:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/src/Driver.cpp.i
.PHONY : src/Driver.cpp.i

src/Driver.s: src/Driver.cpp.s

.PHONY : src/Driver.s

# target to generate assembly for a file
src/Driver.cpp.s:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/src/Driver.cpp.s
.PHONY : src/Driver.cpp.s

src/Instruccion.obj: src/Instruccion.cpp.obj

.PHONY : src/Instruccion.obj

# target to build an object file
src/Instruccion.cpp.obj:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/src/Instruccion.cpp.obj
.PHONY : src/Instruccion.cpp.obj

src/Instruccion.i: src/Instruccion.cpp.i

.PHONY : src/Instruccion.i

# target to preprocess a source file
src/Instruccion.cpp.i:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/src/Instruccion.cpp.i
.PHONY : src/Instruccion.cpp.i

src/Instruccion.s: src/Instruccion.cpp.s

.PHONY : src/Instruccion.s

# target to generate assembly for a file
src/Instruccion.cpp.s:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/src/Instruccion.cpp.s
.PHONY : src/Instruccion.cpp.s

src/Programa.obj: src/Programa.cpp.obj

.PHONY : src/Programa.obj

# target to build an object file
src/Programa.cpp.obj:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/src/Programa.cpp.obj
.PHONY : src/Programa.cpp.obj

src/Programa.i: src/Programa.cpp.i

.PHONY : src/Programa.i

# target to preprocess a source file
src/Programa.cpp.i:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/src/Programa.cpp.i
.PHONY : src/Programa.cpp.i

src/Programa.s: src/Programa.cpp.s

.PHONY : src/Programa.s

# target to generate assembly for a file
src/Programa.cpp.s:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/src/Programa.cpp.s
.PHONY : src/Programa.cpp.s

tests/test_driver.obj: tests/test_driver.cpp.obj

.PHONY : tests/test_driver.obj

# target to build an object file
tests/test_driver.cpp.obj:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/tests/test_driver.cpp.obj
.PHONY : tests/test_driver.cpp.obj

tests/test_driver.i: tests/test_driver.cpp.i

.PHONY : tests/test_driver.i

# target to preprocess a source file
tests/test_driver.cpp.i:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/tests/test_driver.cpp.i
.PHONY : tests/test_driver.cpp.i

tests/test_driver.s: tests/test_driver.cpp.s

.PHONY : tests/test_driver.s

# target to generate assembly for a file
tests/test_driver.cpp.s:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/tests/test_driver.cpp.s
.PHONY : tests/test_driver.cpp.s

tests/test_instruccion.obj: tests/test_instruccion.cpp.obj

.PHONY : tests/test_instruccion.obj

# target to build an object file
tests/test_instruccion.cpp.obj:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/tests/test_instruccion.cpp.obj
.PHONY : tests/test_instruccion.cpp.obj

tests/test_instruccion.i: tests/test_instruccion.cpp.i

.PHONY : tests/test_instruccion.i

# target to preprocess a source file
tests/test_instruccion.cpp.i:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/tests/test_instruccion.cpp.i
.PHONY : tests/test_instruccion.cpp.i

tests/test_instruccion.s: tests/test_instruccion.cpp.s

.PHONY : tests/test_instruccion.s

# target to generate assembly for a file
tests/test_instruccion.cpp.s:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/tests/test_instruccion.cpp.s
.PHONY : tests/test_instruccion.cpp.s

tests/test_programa.obj: tests/test_programa.cpp.obj

.PHONY : tests/test_programa.obj

# target to build an object file
tests/test_programa.cpp.obj:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/tests/test_programa.cpp.obj
.PHONY : tests/test_programa.cpp.obj

tests/test_programa.i: tests/test_programa.cpp.i

.PHONY : tests/test_programa.i

# target to preprocess a source file
tests/test_programa.cpp.i:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/tests/test_programa.cpp.i
.PHONY : tests/test_programa.cpp.i

tests/test_programa.s: tests/test_programa.cpp.s

.PHONY : tests/test_programa.s

# target to generate assembly for a file
tests/test_programa.cpp.s:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/tests/test_programa.cpp.s
.PHONY : tests/test_programa.cpp.s

tests/test_trie.obj: tests/test_trie.cpp.obj

.PHONY : tests/test_trie.obj

# target to build an object file
tests/test_trie.cpp.obj:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/tests/test_trie.cpp.obj
.PHONY : tests/test_trie.cpp.obj

tests/test_trie.i: tests/test_trie.cpp.i

.PHONY : tests/test_trie.i

# target to preprocess a source file
tests/test_trie.cpp.i:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/tests/test_trie.cpp.i
.PHONY : tests/test_trie.cpp.i

tests/test_trie.s: tests/test_trie.cpp.s

.PHONY : tests/test_trie.s

# target to generate assembly for a file
tests/test_trie.cpp.s:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/tests/test_trie.cpp.s
.PHONY : tests/test_trie.cpp.s

tests/test_ventana.obj: tests/test_ventana.cpp.obj

.PHONY : tests/test_ventana.obj

# target to build an object file
tests/test_ventana.cpp.obj:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/tests/test_ventana.cpp.obj
.PHONY : tests/test_ventana.cpp.obj

tests/test_ventana.i: tests/test_ventana.cpp.i

.PHONY : tests/test_ventana.i

# target to preprocess a source file
tests/test_ventana.cpp.i:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/tests/test_ventana.cpp.i
.PHONY : tests/test_ventana.cpp.i

tests/test_ventana.s: tests/test_ventana.cpp.s

.PHONY : tests/test_ventana.s

# target to generate assembly for a file
tests/test_ventana.cpp.s:
	$(MAKE) -f CMakeFiles\correrTests.dir\build.make CMakeFiles/correrTests.dir/tests/test_ventana.cpp.s
.PHONY : tests/test_ventana.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... install/strip
	@echo ... correrTests
	@echo ... install/local
	@echo ... install
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... list_install_components
	@echo ... gtest
	@echo ... gtest_main
	@echo ... src/Calculadora.obj
	@echo ... src/Calculadora.i
	@echo ... src/Calculadora.s
	@echo ... src/Driver.obj
	@echo ... src/Driver.i
	@echo ... src/Driver.s
	@echo ... src/Instruccion.obj
	@echo ... src/Instruccion.i
	@echo ... src/Instruccion.s
	@echo ... src/Programa.obj
	@echo ... src/Programa.i
	@echo ... src/Programa.s
	@echo ... tests/test_driver.obj
	@echo ... tests/test_driver.i
	@echo ... tests/test_driver.s
	@echo ... tests/test_instruccion.obj
	@echo ... tests/test_instruccion.i
	@echo ... tests/test_instruccion.s
	@echo ... tests/test_programa.obj
	@echo ... tests/test_programa.i
	@echo ... tests/test_programa.s
	@echo ... tests/test_trie.obj
	@echo ... tests/test_trie.i
	@echo ... tests/test_trie.s
	@echo ... tests/test_ventana.obj
	@echo ... tests/test_ventana.i
	@echo ... tests/test_ventana.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

